In [1]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)
from transformerModule import PositionalEncoding, MultiHeadAttention, MultiHeadedAttention

input = torch.randn(20,5,512)
mul_att1 = MultiHeadAttention(2,512,0.1)
mul_att_out1 = mul_att1.forward(input.float())
# 模块参数
# print(mul_att1.state_dict())
for name1, param1 in mul_att1.named_parameters():
    print(name1, param1)
# 模块结果
# print(mul_att_out1)

Wq.weight Parameter containing:
tensor([[ 0.0438,  0.0417,  0.0138,  ...,  0.0407,  0.0223, -0.0045],
        [ 0.0427, -0.0282,  0.0220,  ...,  0.0039,  0.0165,  0.0181],
        [ 0.0105, -0.0399, -0.0341,  ..., -0.0398, -0.0172, -0.0029],
        ...,
        [-0.0063, -0.0160,  0.0012,  ...,  0.0116, -0.0342,  0.0227],
        [-0.0274,  0.0040,  0.0228,  ..., -0.0257, -0.0359, -0.0326],
        [ 0.0211, -0.0106, -0.0284,  ..., -0.0357, -0.0277,  0.0082]],
       requires_grad=True)
Wq.bias Parameter containing:
tensor([ 0.0323,  0.0218, -0.0249,  0.0071, -0.0199,  0.0223, -0.0187, -0.0119,
        -0.0080,  0.0340,  0.0024,  0.0006,  0.0293,  0.0192,  0.0269,  0.0031,
        -0.0241, -0.0003, -0.0028, -0.0090, -0.0308, -0.0005, -0.0335,  0.0395,
         0.0006, -0.0180, -0.0216, -0.0326, -0.0248,  0.0086,  0.0315,  0.0202,
        -0.0064, -0.0043,  0.0187,  0.0043, -0.0299, -0.0398,  0.0149, -0.0175,
        -0.0304,  0.0187,  0.0262,  0.0326, -0.0008, -0.0225, -0.0121, -0.041

In [3]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)
from transformerModule import PositionalEncoding, MultiHeadAttention, MultiHeadedAttention

input = torch.randn(20,5,512)
mul_att1 = MultiHeadedAttention(2,512,0.1)
mul_att_out1 = mul_att1.forward(input.float(), input.float(), input.float())
# 模块参数
# print(mul_att1.state_dict())
for name1, param1 in mul_att1.named_parameters():
    print(name1, param1)
# 模块结果
# print(mul_att_out1)

linear_layers.0.weight Parameter containing:
tensor([[ 0.0438,  0.0417,  0.0138,  ...,  0.0407,  0.0223, -0.0045],
        [ 0.0427, -0.0282,  0.0220,  ...,  0.0039,  0.0165,  0.0181],
        [ 0.0105, -0.0399, -0.0341,  ..., -0.0398, -0.0172, -0.0029],
        ...,
        [-0.0063, -0.0160,  0.0012,  ...,  0.0116, -0.0342,  0.0227],
        [-0.0274,  0.0040,  0.0228,  ..., -0.0257, -0.0359, -0.0326],
        [ 0.0211, -0.0106, -0.0284,  ..., -0.0357, -0.0277,  0.0082]],
       requires_grad=True)
linear_layers.0.bias Parameter containing:
tensor([ 0.0323,  0.0218, -0.0249,  0.0071, -0.0199,  0.0223, -0.0187, -0.0119,
        -0.0080,  0.0340,  0.0024,  0.0006,  0.0293,  0.0192,  0.0269,  0.0031,
        -0.0241, -0.0003, -0.0028, -0.0090, -0.0308, -0.0005, -0.0335,  0.0395,
         0.0006, -0.0180, -0.0216, -0.0326, -0.0248,  0.0086,  0.0315,  0.0202,
        -0.0064, -0.0043,  0.0187,  0.0043, -0.0299, -0.0398,  0.0149, -0.0175,
        -0.0304,  0.0187,  0.0262,  0.0326, -0.0008

In [18]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

input = torch.randn(20,5)

linear1 = nn.Linear(5,2)
param1 = linear1.state_dict()

seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

linear2 = nn.Linear(5,2)
# linear2.load_state_dict(param1)

output1 = linear1(input)
output2 = linear2(input)

In [23]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

input = torch.randn(20,5)



linear2 = nn.Linear(5,2)


output2 = linear2(input)

In [19]:
output1

tensor([[ 0.8670,  0.2194],
        [ 0.4261, -0.2586],
        [ 0.2927,  0.3177],
        [ 0.3878, -0.0392],
        [ 0.1735,  0.5971],
        [ 0.2066,  0.5253],
        [ 0.1987, -0.3484],
        [ 0.1141, -0.8061],
        [-0.2912, -0.6373],
        [ 0.7464,  0.2669],
        [ 0.9938,  0.1806],
        [ 0.3014, -0.4113],
        [ 0.2747, -0.0263],
        [ 0.4468,  0.0230],
        [ 0.3481, -0.5977],
        [ 0.1460, -0.1030],
        [ 0.0869, -0.0359],
        [ 0.0924, -0.6097],
        [-0.0361, -0.1957],
        [ 0.7113,  0.3588]], grad_fn=<AddmmBackward0>)

In [24]:
output2

tensor([[ 0.8670,  0.2194],
        [ 0.4261, -0.2586],
        [ 0.2927,  0.3177],
        [ 0.3878, -0.0392],
        [ 0.1735,  0.5971],
        [ 0.2066,  0.5253],
        [ 0.1987, -0.3484],
        [ 0.1141, -0.8061],
        [-0.2912, -0.6373],
        [ 0.7464,  0.2669],
        [ 0.9938,  0.1806],
        [ 0.3014, -0.4113],
        [ 0.2747, -0.0263],
        [ 0.4468,  0.0230],
        [ 0.3481, -0.5977],
        [ 0.1460, -0.1030],
        [ 0.0869, -0.0359],
        [ 0.0924, -0.6097],
        [-0.0361, -0.1957],
        [ 0.7113,  0.3588]], grad_fn=<AddmmBackward0>)