In [3]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)
from transformerModule import PositionalEncoding, MultiHeadAttention, MultiHeadedAttention

input = torch.randn(20,5,512)
mul_att1 = MultiHeadAttention(2,512,0.1)
mul_att_out1 = mul_att1.forward(input.float())
# 模块参数
# print(mul_att1.state_dict())
# for name1, param1 in mul_att1.named_parameters():
#     print(name1, param1)
# 模块结果
print(mul_att_out1)

tensor([[[ 0.0912,  0.0242, -0.0067,  ...,  0.0329,  0.0298, -0.1147],
         [ 0.0216,  0.0816, -0.0537,  ...,  0.1017,  0.0418, -0.2685],
         [-0.0189,  0.0255,  0.0096,  ...,  0.0613,  0.0503, -0.2193],
         [ 0.0119,  0.0492, -0.0382,  ..., -0.0119,  0.0535, -0.2352],
         [ 0.0832,  0.0399,  0.0035,  ...,  0.0552,  0.0099, -0.1576]],

        [[ 0.1606, -0.0175,  0.3246,  ...,  0.1131,  0.0707,  0.3990],
         [ 0.1115,  0.0606,  0.1783,  ...,  0.1294, -0.0480,  0.2024],
         [ 0.1033, -0.0319,  0.3518,  ...,  0.0861, -0.0696,  0.4981],
         [ 0.0713, -0.0376,  0.2406,  ...,  0.0457, -0.0945,  0.3883],
         [ 0.1189, -0.0490,  0.3508,  ...,  0.0787, -0.0059,  0.3268]],

        [[ 0.2070, -0.0687,  0.2748,  ..., -0.0871,  0.0087,  0.0167],
         [ 0.1150,  0.0580,  0.1072,  ..., -0.0395,  0.0171,  0.0484],
         [ 0.0861, -0.0493,  0.2033,  ..., -0.0132,  0.0346,  0.0041],
         [ 0.1844, -0.0331,  0.1966,  ..., -0.0746,  0.0686, -0.0212],
  

In [4]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)
from transformerModule import PositionalEncoding, MultiHeadAttention, MultiHeadedAttention

input = torch.randn(20,5,512)
mul_att1 = MultiHeadedAttention(2,512,0.1)
mul_att_out1 = mul_att1.forward(input.float(), input.float(), input.float())
# 模块参数
# print(mul_att1.state_dict())
# for name1, param1 in mul_att1.named_parameters():
#     print(name1, param1)
# 模块结果
print(mul_att_out1)

tensor([[[ 0.0912,  0.0242, -0.0067,  ...,  0.0329,  0.0298, -0.1147],
         [ 0.0216,  0.0816, -0.0537,  ...,  0.1017,  0.0418, -0.2685],
         [-0.0189,  0.0255,  0.0096,  ...,  0.0613,  0.0503, -0.2193],
         [ 0.0119,  0.0492, -0.0382,  ..., -0.0119,  0.0535, -0.2352],
         [ 0.0832,  0.0399,  0.0035,  ...,  0.0552,  0.0099, -0.1576]],

        [[ 0.1606, -0.0175,  0.3246,  ...,  0.1131,  0.0707,  0.3990],
         [ 0.1115,  0.0606,  0.1783,  ...,  0.1294, -0.0480,  0.2024],
         [ 0.1033, -0.0319,  0.3518,  ...,  0.0861, -0.0696,  0.4981],
         [ 0.0713, -0.0376,  0.2406,  ...,  0.0457, -0.0945,  0.3883],
         [ 0.1189, -0.0490,  0.3508,  ...,  0.0787, -0.0059,  0.3268]],

        [[ 0.2070, -0.0687,  0.2748,  ..., -0.0871,  0.0087,  0.0167],
         [ 0.1150,  0.0580,  0.1072,  ..., -0.0395,  0.0171,  0.0484],
         [ 0.0861, -0.0493,  0.2033,  ..., -0.0132,  0.0346,  0.0041],
         [ 0.1844, -0.0331,  0.1966,  ..., -0.0746,  0.0686, -0.0212],
  

In [18]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

input = torch.randn(20,5)

linear1 = nn.Linear(5,2)
param1 = linear1.state_dict()

seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

linear2 = nn.Linear(5,2)
# linear2.load_state_dict(param1)

output1 = linear1(input)
output2 = linear2(input)

In [23]:
import numpy as np
import torch.nn as nn
import torch
import torch.optim as optim
import math
seed = 32
np.random.seed(seed) 
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)

input = torch.randn(20,5)



linear2 = nn.Linear(5,2)


output2 = linear2(input)

In [19]:
output1

tensor([[ 0.8670,  0.2194],
        [ 0.4261, -0.2586],
        [ 0.2927,  0.3177],
        [ 0.3878, -0.0392],
        [ 0.1735,  0.5971],
        [ 0.2066,  0.5253],
        [ 0.1987, -0.3484],
        [ 0.1141, -0.8061],
        [-0.2912, -0.6373],
        [ 0.7464,  0.2669],
        [ 0.9938,  0.1806],
        [ 0.3014, -0.4113],
        [ 0.2747, -0.0263],
        [ 0.4468,  0.0230],
        [ 0.3481, -0.5977],
        [ 0.1460, -0.1030],
        [ 0.0869, -0.0359],
        [ 0.0924, -0.6097],
        [-0.0361, -0.1957],
        [ 0.7113,  0.3588]], grad_fn=<AddmmBackward0>)

In [24]:
output2

tensor([[ 0.8670,  0.2194],
        [ 0.4261, -0.2586],
        [ 0.2927,  0.3177],
        [ 0.3878, -0.0392],
        [ 0.1735,  0.5971],
        [ 0.2066,  0.5253],
        [ 0.1987, -0.3484],
        [ 0.1141, -0.8061],
        [-0.2912, -0.6373],
        [ 0.7464,  0.2669],
        [ 0.9938,  0.1806],
        [ 0.3014, -0.4113],
        [ 0.2747, -0.0263],
        [ 0.4468,  0.0230],
        [ 0.3481, -0.5977],
        [ 0.1460, -0.1030],
        [ 0.0869, -0.0359],
        [ 0.0924, -0.6097],
        [-0.0361, -0.1957],
        [ 0.7113,  0.3588]], grad_fn=<AddmmBackward0>)