In [6]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
seed = 6
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

input = torch.Tensor([[1, 2, 3],[4, 5, 6]])
input.shape
linear_layer = nn.Linear(3, 2)
linear_layer2 = nn.Linear(3, 4)
custom_weights = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=torch.float32)
custom_bias = torch.tensor([0.5, -0.5], dtype=torch.float32)

with torch.no_grad():
    linear_layer.weight = torch.nn.Parameter(custom_weights)
    linear_layer.bias = torch.nn.Parameter(custom_bias)
output2 = linear_layer2(input)
output2

tensor([[-1.6639,  0.9495,  1.4512, -0.6586],
        [-3.1852,  2.2217,  2.7003, -1.6157]], grad_fn=<AddmmBackward0>)

In [3]:
linear_layer(input)

tensor([[14.5000, 31.5000],
        [32.5000, 76.5000]], grad_fn=<AddmmBackward0>)

In [7]:
linear_layer2.weight

Parameter containing:
tensor([[ 0.0694, -0.3841, -0.1925],
        [-0.0407,  0.1539,  0.3109],
        [-0.3294,  0.3250,  0.4208],
        [ 0.1214, -0.1559, -0.2845]], requires_grad=True)

In [8]:
linear_layer2.weight

Parameter containing:
tensor([[ 0.0694, -0.3841, -0.1925],
        [-0.0407,  0.1539,  0.3109],
        [-0.3294,  0.3250,  0.4208],
        [ 0.1214, -0.1559, -0.2845]], requires_grad=True)

In [10]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(10, 5)  # 输入特征数为10，输出特征数为5
        self.fc2 = nn.Linear(5, 2)   # 输入特征数为5，输出特征数为2
 
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x
 
# 实例化网络
model = SimpleNet()
 
# 获取所有参数
for name, param in model.named_parameters():
    print(name, param.data)

fc1.weight tensor([[-0.0380,  0.1043, -0.0491, -0.2470,  0.3125,  0.3058, -0.1567, -0.0977,
         -0.1836,  0.1747],
        [ 0.1561,  0.1063, -0.0985,  0.0144,  0.2049,  0.0887,  0.2992,  0.1330,
         -0.2308, -0.2579],
        [ 0.1911, -0.0560, -0.1233,  0.1661, -0.0762, -0.2388, -0.1307, -0.0341,
         -0.0957,  0.0807],
        [-0.0858,  0.3147,  0.1189, -0.1590, -0.1759, -0.1321,  0.1925, -0.1182,
          0.0136,  0.2428],
        [-0.0915, -0.0227, -0.1638,  0.2670,  0.1082, -0.0386, -0.1424,  0.2573,
          0.1697,  0.0971]])
fc1.bias tensor([ 0.1652,  0.2677,  0.1164, -0.2768, -0.1126])
fc2.weight tensor([[-0.1589,  0.4457,  0.2211, -0.2520,  0.1845],
        [-0.2141,  0.4138, -0.1269,  0.1480,  0.2971]])
fc2.bias tensor([ 0.3158, -0.1042])


In [11]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 67
